# General Jekyll Config
highlighter: rouge
url: http://debeando.com
lsi: false
exclude: [CNAME, .gitignore, Gemfile, Gemfile.lock]
incremental: true
permalink: /:title:output_ext
exclude:
  - "README.md"
  - "vendor"
